program: mbrl.examples.main  # not a script to run but a module to run

method: bayes  # grid, random, bayes
metric:
  name: episode_reward  # what to optimize
  goal: maximize  # maximize / minimize

# hyperparameter to search in - look at example_config.yaml where a cfg of a run was printed
parameters:
  dynamics_model.ensemble_size:
    values: [9, 8, 4] 

command:
  - ${env}
  - python
  - -m
  - ${program}
  - ${args_no_hyphens}


early_terminate: 
  type: hyperband  # hyperband, median, none
  max_iter: 27  # max iterations

# number of runs in the sweep
total_runs: 3  