# @package _group_
_target_: mbrl.models.VBLLEnsemble
ensemble_size: 3
device: ${device}
propagation_method: random_model
clip_val: 
no_thompson_heads: 75 # if 0, then no thompson sampling, if > 0, then thompson sampling with that many heads

member_cfg:
  _target_: mbrl.models.VBLLMLP
  device: ${device}
  in_size: ???
  out_size: ???
  deterministic: false
  recursive_num_epochs: 0
  
  activation_fn_cfg:
    _target_: torch.nn.ELU

  num_layers: 6
  hid_size: 200
  feature_dim: 64
  regularization_weight_factor: 0.25
  parameterization: "dense_precision"
  cov_rank: 1 
  prior_scale: 5.2
  wishart_scale: 0.45