# @package _group_
_target_: mbrl.models.BasicEnsemble
ensemble_size: 1
device: ${device}
propagation_method: random_model
member_cfg:
  _target_: mbrl.models.VBLLMLP
  device: ${device}
  num_layers: 4
  in_size: ???
  out_size: ???
  hid_size: 50
  deterministic: false
  activation_fn_cfg:
    _target_: torch.nn.ELU

  regularization_weight_factor: 1
  parameterization: "dense" 
  cov_rank: 1 
  prior_scale: 1.
  wishart_scale: 1.