# @package _group_
_target_: mbrl.models.BasicEnsemble
ensemble_size: 1
device: ${device}
propagation_method: random_model
clip_val: 

member_cfg:
  _target_: mbrl.models.VBLLMLP
  device: ${device}
  in_size: ???
  out_size: ???
  deterministic: false
  
  activation_fn_cfg:
    _target_: torch.nn.ELU

  num_layers: 4
  hid_size: 200
  feature_dim: 50
  regularization_weight_factor: 1
  parameterization: "dense" 
  cov_rank: 1 
  prior_scale: 1.
  wishart_scale: 1.